services:

  backbone:
    build: component/backbone
    ports:
      - "5070:5070/tcp"
    volumes:
      - ./docker/backbone.conf:/etc/upbx.conf
    restart: unless-stopped

  gateway:
    build: component/gateway
    ports:
      - "5060:5060/udp"
      - "10000-10099:10000-10099/udp"
    volumes:
      - ./docker/gateway.conf:/etc/upbx-gw.conf
      - ./data:/var/lib/upbx/gateway
    depends_on:
      - backbone
    restart: unless-stopped

  trunk:
    build: component/trunk
    ports:
      - "5062:5062/udp"
      - "20000-20099:20000-20099/udp"
    volumes:
      - ./docker/trunk.conf:/etc/upbx-trk.conf
    depends_on:
      - backbone
    restart: unless-stopped
